### ISSUE TITLE
[Proposta] Inserir o GER nas atividades extra curriculares

### ISSUE THREAD

**Issue by marcelomjr** [AAACEC/bixos-landing-page#2]
Boa tarde nós do GER (Grupo de Estudos em Robótica), queremos solicitar que a Atlética nos inclua em seu site de divulgação aos bixos.
Se for possível, aqui estão algumas informações que podem ser utilizadas para nossa divulgação:
"O GER (Grupo de Estudos em Robótica), cujos membros são alunos dos cursos de Ciência e Engenharia de Computação e Engenharia de Controle e Automação participam anualmente de competições como a CBR e a Freescale Cup, além de realizar outros projetos relacionados com robótica.
https://www.facebook.com/unicampger"

**Comment by marcelomjr** [comment]
Dessa forma o texto fica melhor e mais curto se vocês preferirem:
"O GER é um grupo de robótica autônoma, cujos membros são alunos de Ciência e Engenharia da Computação e Engenharia de Controle e Automação. Participam anualmente de competições como a CBR e a Freescale Cup, além de realizar outros projetos como Drone e Impressora 3D.
https://www.facebook.com/unicampger"

Obrigado

Marcelo Martimiano Junior

**Comment by rmobis** [comment]
Acho que o melhor seria colocar como uma entidade, junto com o resto.

Da pra colocar o GPSL (Grupo Pró Software Livre) também e mudar o layout
pra mostrar 4 em cada linha.

Que que você acha @dsfugimoto?

**Comment by dsfugimoto** [comment]
Acho válido sim incluirmos isso @rmobis e @marcelomjr !
Só preciso que me enviem a marca de vocês vetorizada!

**Comment by marcelomjr** [comment]
Aqui está o logo também:
![logo1](https://cloud.githubusercontent.com/assets/8458316/6094344/bbcca9e4-af0d-11e4-9b1e-678aeb06acbe.png)

**Comment by dsfugimoto** [comment]
@marcelomjr , 

Já fiz as alterações, mas o texto teve de ficar encolhido: "Grupo de robótica autônoma com membros do curso de Computação e Engenharia de Controle e Automação. Participam anualmente de competições (CBR, Freescale Cup), além de realizar outros projetos."

Se estiver tudo bem pra você, posso enviar pro repositório agora as modificações (:

**Comment by marcelomjr** [comment]
Essa imagem serve?

**Comment by marcelomjr** [comment]
Tudo bem sim David
Obrigado!

Em 7 de fevereiro de 2015 22:54, David Fugimoto notifications@github.com
escreveu:

**Comment by rmobis** [comment]
Upado no servidor.
