### ISSUE TITLE
Scroll no mapa

### ISSUE THREAD

**Issue by thiagoelg** [AAACEC/bixos-landing-page#4]
Fazendo o scroll no site, quando chega no mapa, o scroll é interrompido caso o mouse esteja na região do mapa, pois o Google Maps toma conta da função, forçando o usuário a mover o mouse para o canto da tela para continuar o scroll.
Não é nada crítico, mas interrompe a navegação.

Sugestões:
- Diminuir o tamanho do mapa (não resolve o problema, mas diminui a chance do mouse estar dentro do mapa);
- Adicionar um delay para que o Google Maps tome conta do mouse (não sei se é possível);
- Desabilitar a função scroll to zoom do Google Maps;
- Deixar quieto.

![](http://4st.me/gwEAJ.png)

**Comment by rmobis** [comment]
Tinha reparado nisso também. Acho que o melhor seria disabilitar o scroll to zoom no mapa e forçar o uso do widget. Vou ver como fazer isso.

**Comment by rmobis** [comment]
Corrigido e upado no servidor.
